services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - ADDRESS=0.0.0.0
      - PORT=8080
      - DB_URL=postgres://api:api@db:5432/api?sslmode=disable
    volumes:
      - ./conf:/opt/conf
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "psql -U api -d api"]
      interval: 1s
      timeout: 30s
      retries: 15
